In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
slice_of_arr = arr[0:6]

In [6]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [7]:
slice_of_arr[:] = 99

In [8]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy_slice = arr_copy[0:6]

In [19]:
arr_copy [:] = 1

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
# Copy || Indexing a 2D array

In [22]:
arr_2d = np.array([[5,10,15],[20,35,30],[35,40,45]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 35, 30],
       [35, 40, 45]])

In [24]:
arr_2d[0][0]

5

In [26]:
arr_2d[0,0] # Another way to access 2D Arrays

5

In [28]:
arr_2d[:2,1:]

array([[10, 15],
       [35, 30]])

In [40]:
arr_2d_2 = np.arange(50).reshape(5,10)

In [41]:
arr_2d_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d_2[2:3,2:5]

array([[22, 23, 24]])