In [14]:
my_list = [1,2,3]

In [15]:
import numpy as np

In [16]:
arr = np.array(my_list)

In [17]:
arr

array([1, 2, 3])

In [18]:
my_mat = [[1,2,3],[4,5,6],[1,2,3]]

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((2,5)) # Rows n Columns generated

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((1,3))

array([[1., 1., 1.]])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5,5)

array([[0.85606447, 0.58585604, 0.73198903, 0.33952259, 0.98564585],
       [0.14775461, 0.0816176 , 0.9987932 , 0.84929117, 0.95064987],
       [0.82142253, 0.22002085, 0.21163375, 0.9868356 , 0.6905756 ],
       [0.63088313, 0.16252653, 0.86271728, 0.10590024, 0.16486807],
       [0.20868425, 0.06138083, 0.11715466, 0.01014642, 0.69979967]])

In [28]:
np.random.randn(5,5)

array([[ 0.01832653, -0.13947987,  1.0741954 , -0.91607084,  0.39418413],
       [ 2.45831771,  0.03385476,  0.2652155 , -0.84514836, -1.6954271 ],
       [-0.42341447, -0.29143974, -0.07797687, -1.12744689, -2.39797097],
       [ 1.38391602,  0.47403623, -0.18057175,  0.39928353,  0.36147248],
       [ 0.53894751,  0.33357322,  0.43971148,  0.19817099,  0.63840701]])

In [31]:
np.random.randint(1,12)

11

In [32]:
arr = np.arange(25)

In [33]:
ranarr = np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr

array([31, 11, 33, 25, 29,  3,  9, 35,  2, 24])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

35

In [38]:
ranarr.min()

2

In [39]:
ranarr.argmax()

7

In [40]:
ranarr.shape

(10,)

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')